### ISSUE TITLE
uninitialized constant PLSQL::PipelinedFunction

### ISSUE THREAD

**Issue by pivotal-sharknado** [flash-gordon/rails-plsql#4]
Hello, 

We're having issues using this gem. We're using jruby 1.7.6 and when we try to `rails c` the application blows up on requiring the gem. This is the error we're getting:

NameError: uninitialized constant PLSQL::PipelinedFunction
from /Users/pivotal/.rvm/gems/jruby-1.7.6/bundler/gems/rails-plsql-ec5f42af06ac/lib/active_record/plsql/pipelined.rb:47:in `pipelined_function='

We can't find the declaration of PLSQL::PipelinedFunction in the gem, the ruby-plsql gem or the oracle-enhanced gem. Perhaps we're using different versions.

We'd really like to be able to use this, any help is appreciated.

Cheers

Robbie and Nigel

**Comment by pivotal-sharknado** [comment]
We added your ruby-plsql to our gemset but are now getting this error

oMethodError: undefined method `select_first' for nil:NilClass
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/bundler/gems/ruby-plsql-4826c9bde68d/lib/plsql/sql_statements.rb:5:in`select_first'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/bundler/gems/ruby-plsql-4826c9bde68d/lib/plsql/procedure.rb:13:in `find_procedure_in_schema'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/bundler/gems/ruby-plsql-4826c9bde68d/lib/plsql/procedure.rb:8:in`find'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/bundler/gems/rails-plsql-ec5f42af06ac/lib/active_record/plsql/procedure_methods.rb:104:in `find_procedure'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/bundler/gems/rails-plsql-ec5f42af06ac/lib/active_record/plsql/procedure_methods.rb:68:in`procedure_method'
    from /Users/pivotal/workspace/sellout/app/models/annual_inventory.rb:4:in `AnnualInventory'
    from /Users/pivotal/workspace/sellout/app/models/annual_inventory.rb:1:in`(root)'
    from org/jruby/RubyKernel.java:1101:in `load'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:1:in`(root)'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:469:in `load_file'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:639:in`new_constants_in'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:468:in `load_file'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:353:in`require_or_load'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:502:in `load_missing_constant'
    from org/jruby/RubyArray.java:1613:in`each'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:192:in `const_missing'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:190:in`const_missing'
    from org/jruby/RubyKernel.java:1121:in `eval'
    from (irb):5:in`evaluate'
    from org/jruby/RubyKernel.java:1517:in `loop'
    from org/jruby/RubyKernel.java:1282:in`catch'
    from org/jruby/RubyKernel.java:1282:in `catch'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/railties-3.2.15/lib/rails/commands/console.rb:47:in`start'
    from /Users/pivotal/.rvm/gems/jruby-1.7.6/gems/railties-3.2.15/lib/rails/commands/console.rb:8:in `start'
    from org/jruby/RubyKernel.java:1082:in`require'
    from scriptexit

**Comment by flash-gordon** [comment]
Hi.
What branch are you using? Try this: https://github.com/flash-gordon/ruby-plsql/tree/current
Also backtrace points at line

``` ruby
module PLSQL
  module SQLStatements
    # Select first row as array or values (without column names)
    def select_first(sql, *bindvars)
      @connection.select_first(sql, *bindvars) # <-- boom!
    end
...
```

which means that you did not set connection object. Please check it.

Here how I initialize connection in my non-Rails environment (using ActiveRecord though):

``` ruby
tns = ENV['TESTS_DB_TNS']
raise RuntimeError, 'Missing DB TNS name. Please set TESTS_DB_TNS environment variable' if tns.nil? || tns.empty?

username = 'ais_net'
password = ENV['TESTS_DB_PASSWORD']

ActiveRecord::Base.establish_connection(
    :adapter  => 'oracle_enhanced',
    :encoding => 'utf8',
    :database => tns,
    :username => username,
    :password => password)

plsql.activerecord_class = ActiveRecord::Base
```

And in Rails projects:

``` ruby
# config/initializers/ruby_plsql_set_connection.rb
plsql.activerecord_class = ActiveRecord::Base
```

If you want to work with JDBC driver directly you can use code from oracle enhanced adapter gem (https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb) as start point.

**Comment by flash-gordon** [comment]
Oh. This rails-plsql not ruby-plsql. So I think you can ignore my advice about JDBC (you must already have ActiveRecord in your runtime environment).

**Comment by robb1e** [comment]
Yeah we're using Rails and the current branch of flash-gordon/ruby-plsql so I would expect the connection to be set, but we can check that. 

We actually ended up writing the SQL and running through `ActiveRecord::Base.connection.select_all` to hit the function which worked well. We just had to serialize the results but then we lose all the ActiveRecord niceties.

**Comment by flash-gordon** [comment]
AR internally calls YourModelClassName#find_by_sql(sql, binds) after obtaining SQL from AR::Relation. So actually you can call it manually and it will return model objects but I think you won't able to work with associations though.

**Comment by pivotal-sharknado** [comment]
Nice, we'll give that a try. I think we can close this issue for now though. 

Thanks

**Comment by davidrenne** [comment]
The original issue about the constants is that flash-gordon's local gem environment has his fork of ruby-plsql checked out and so it must be that his gemspec is just using his local fork.

To get around the original constant issue you must:

```
gem 'ruby-plsql', :git => 'https://github.com/flash-gordon/ruby-plsql.git'
gem 'rails-plsql', :git => 'https://github.com/flash-gordon/rails-plsql.git'
```

I would suggest that maybe to simplify things, maybe @flash-gordon can publish a new gem called ruby-plsql-gordon to rubygems.org with his files in there for pipeline functions and add that to the main gemspec of the rails-plsql project.

Once I added that to test and also added his initializer

```
plsql.activerecord_class = ActiveRecord::Base
```

The initializer snippet should be in his README.md so developers can try it out quickly without too much headache to use his (hopefully) excellent code to solve my pipeline function.

I wrote a pipeline function that will join a bunch of tables and filter down appropriately. 

Since rails models suck with global scoping and also with not being able to use anything in the session with models,  I am planning on trying this gem out with my new pipeline function to see if I can filter the primary model's data by joining down to multiple tables and passing along the filter assigned to the user.

**Comment by flash-gordon** [comment]
Yep, I was hoping that my pull request to ruby-plsql would be merged... I'll fix README and/or push my version of ruby-plsql gem. It will also include nice PL/SQL calls logging.

**Comment by davidrenne** [comment]
I wish it could get merged and deployed to ruby gems faster.  So far my usage is working with this gem and it would be nice to use a real gem package instead of a git clone because passenger doesn't seem to like git gemfiles —
Dave

**Comment by davidrenne** [comment]
Also, not sure if you can help with this, but I am noticing that in my
first implementation of a pipeline function that returns a row.  My primary
keys are getting casted into a float number.  So for PK 10000.  The
underlying data is coming back as 10000.0.

Any help would be much appreciated if you have any clue how that can be
fixed.  I just did xxxx.id.to_int in my view for each iteration of the
results into a local variable.

**Comment by flash-gordon** [comment]
It depends on your PK naming convention and adapter pereferences. Look here for details: https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L309
